### PR TITLE
Update README.md and config.js to be more accessible to beginners

### PR DESCRIPTION
**Pull request by druttka**
In my experience getting started with this example, the example endpoint format `*.graphs.azure.com` led to some uncertainty. The endpoints I saw were of the formats `*.gremlin.cosmosdb.azure.com` and `*.documents.azure.com`. The gremlin endpoint worked for me. 

While updating that example endpoint format, I considered that making similar changes for consistency in config.js might help new users recognize more quickly what they would need to change.

### CODE REVIEW

**Comment by druttka** [comment]
@LuisBosquez @arramac  I was hoping to get your thoughts on this PR. I see that the `config.endpoint` value was recently updated to show the full endpoint format, and that is great! I feel that a further combination of updating the README and more explicitly marking the placeholder values in `config.js` could make the example more consumable for beginners. Thanks!

**Comment by LuisBosquez** [comment]
Hello @druttka! Would you mind rebasing your PR so I can merge the changes on the `config.js` file? since we have already updated the endpoint suffix.

Thanks!
Luis

**Comment by druttka** [comment]
Thanks @LuisBosquez. I believe my branch is now rebased on top of the latest changes. Were there other changes you were looking for, or did you want me to undo the changes to use this `{placeholder}` style in config.js? I don't have a strong opinion on the placeholder format, so I'm happy to put back the `ALLCAPS` style if that's what you were after.

**Comment by LuisBosquez** [comment]
Thanks @druttka !

**Pull request merged**
